linters:
  enable-all: true
  disable:
    - contextcheck # too many false positives
    - deadcode # deprecated (since v1.49.0) and replaced by 'unused'
    - depguard # checks if package imports are whitelisted
    - exhaustivestruct # deprecated (since v1.46.0) and replaced by 'exhaustruct'
    - exhaustruct # TODO enable and fix, use regex to exclude certain cases
    - godox # TODO enable and fix
    - golint # deprecated (since v1.41.0) and replaced by 'revive'
    - ifshort # deprecated (since v1.48.0)
    - interfacer # deprecated (since v1.38.0)
    - ireturn # TODO enable and fix
    - maligned # deprecated (since v1.38.0)
    - nlreturn # too strict and mostly code is not more readable
    - nosnakecase  # deprecated (since v1.48.1) and replaced by 'revive'
    - scopelint # deprecated (since v1.39.0) and replaced by 'exportloopref'
    - structcheck # deprecated (since v1.49.0) and replaced by 'unused'
    - sqlclosecheck # not needed for this project
    - varcheck # deprecated (since v1.49.0) and replaced by 'unused'
    - wsl # too strict and mostly code is not more readable
linters-settings:
  stylecheck:
    dot-import-whitelist:
      - github.com/onsi/ginkgo/v2
      - github.com/onsi/gomega
  revive:
    enable-all-rules: false
    severity: error
    rules:
      - name: comment-spacings
        disabled: true
      - name: dot-imports
        severity: warning
        disabled: true
      - name: line-length-limit
        severity: warning
        disabled: true
        arguments: [ 120 ]
  gomoddirectives:
    replace-allow-list:
  funlen:
    lines: 80
  cyclop:
    max-complexity: 20
  nestif:
    min-complexity: 6
  gci:
    sections:
      - standard                                             # Standard packages.
      - default                                              # Imports that could not be matched to another section type.
      - prefix(github.com/kyma-project/lifecycle-manager)    # Imports with the specified prefix.
      - blank                                                # Blank imports.
      - dot                                                  # Dot imports.
    custom-order: true
    skip-generated: true

  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - Client
      - record.EventRecorder
      - client.Object
  wrapcheck:
    ignorePackageGlobs:
      - github.com/kyma-project/lifecycle-manager/pkg/*
      - github.com/kyma-project/lifecycle-manager/internal/*
issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - wrapcheck
    - path: tests/e2e_test/
      linters: [ gci ] # Disable gci due to the test utilities dot import.
    - path: pkg/watcher/certificate_suite_test.go
      linters: [ gci ] # Disable gci due to the test utilities dot import.
    - path: internal/declarative/v2/test/v1/declarative_test.go
      linters: [ gci ] # Disable gci due to the test utilities dot import.
    - path: internal/controller/(control-plane|event-filters|kyma_controller|withwatcher|purge)/(.*)_test.go
      linters: [ gci ] # Disable gci due to the test utilities dot import.
  max-issues-per-linter: 0
  max-same-issues: 0
output:
  sort-results: true
run:
  timeout: 15m
  skip-files:
    - zz_generated.deepcopy.go
